stages:
  - test

test:
  stage: test
  image: node:latest
  before_script:
    - chmod +x setup_env.sh
    - ./setup_env.sh
    - npm install
  script:
    - export NODE_ENV=test
    - node createTestTable.js
    - npm test
  only:
    - merge_requests

# deploy to AWS below?
