stages:
  - test

test:
  stage: test
  image: node:latest
  before_script:
    - chmod +x setup_env.sh
    - ./setup_env.sh
    - npm install
    - node createTestTable.js
  script:
    - npm test
  # only:
  #   - merge_requests
