stages:
  - test
  - lint
  - deploy

test:
  stage: test
  image: node:latest
  before_script:
    - npm install
  script:
    - export NODE_ENV=test
    - export NSG_DB_PASS=$NSG_DB_PASS
    - npm test
  only:
    - merge_requests

eslint:
 stage: lint
 image: node:latest
 script:
    - npm i eslint
    - node_modules/eslint/bin/eslint.js .

deploy:
  stage: deploy
  image: gitlab-registry.nordstrom.com/cicd/images/incubator/artillery:unstable
  before_script:
    - npm install serverless
    - npm install serverless-webpack
  script:
    - creds-helper -aws
    - AWS_PROFILE=arnawsiam046711174152rolensgcirole serverless deploy
  only:
    - merge_requests
