service: nsg-acl

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: us-west-2
  stage: ${opt:stage, 'nonprod'}
  runtime: nodejs10.x
  apiKeys:
    - cloudDBAPI
  tags:
    name: ${self:service}-${self:provider.stage}
  vpc:
    securityGroupIds:
      - sg-0d2e53ade40e60060
    subnetIds:
      - subnet-0126fe03fa91a38de
      - subnet-0386f8ab22bd7a664
  environment:
    NSG_DB_PASS: ${env:DB_PWD}

package:
  individually: true

functions:
  list:
    handler: src/crud.handler
    events:
      - http:
          method: GET
          path: api/table/{table}
          cors: true
          private: true
  create:
    handler: src/crud.handler
    events:
      - http:
          method: POST
          path: api/table/{table}
          cors: true
          private: true
  update:
    handler: src/crud.handler
    events:
      - http:
          method: PUT
          path: api/table/{table}/{id}
          cors: true
          private: true
  delete:
    handler: src/crud.handler
    events:
      - http:
          method: DELETE
          path: api/table/{table}/{id}
          cors: true
          private: true

  token:
    handler: src/token.handler
    events:
      - http:
          method: GET
          path: api/token
          cors: true


custom:
  TeamManagedPolicy: !ImportValue fff000-iam-${self:provider.stage}-nsgtoolbox-01-TeamManagedPolicy
  webpack:
    webpackConfig: webpack.config.js
    includeModules: false

resources:
  Outputs:
    ApiUrl:
      Description: "The API Gateway URL for NSG"
      Value:
        Fn::Join:
          - ""
          - - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com"

plugins:
  - serverless-webpack
