service: nsg-acl

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: us-west-2
  runtime: nodejs10.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - dynamodb:Query
  #       - dynamodb:Scan
  #       - dynamodb:GetItem
  #       - dynamodb:PutItem
  #       - dynamodb:UpdateItem
  #       - dynamodb:DeleteItem
  #     Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

# functions:
#   create:
#     handler: todos/create.create
#     events:
#       - http:
#           path: todos
#           method: post
#           cors: true

#   list:
#     handler: todos/list.list
#     events:
#       - http:
#           path: todos
#           method: get
#           cors: true

#   get:
#     handler: todos/get.get
#     events:
#       - http:
#           path: todos/{id}
#           method: get
#           cors: true

#   update:
#     handler: todos/update.update
#     events:
#       - http:
#           path: todos/{id}
#           method: put
#           cors: true

#   delete:
#     handler: todos/delete.delete
#     events:
#       - http:
#           path: todos/{id}
#           method: delete
#           cors: true

resources:
  Resources:
    ACLTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: prefix-list
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: prefix-list-index
            KeySchema:
              - AttributeName: prefix-list
                KeyType: HASH
            Projection:
              NonKeyAttributes: []
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

