service: orca-api-v${self:custom.version}

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: us-west-2
  stage: ${opt:stage, 'nonprod'}
  runtime: nodejs10.x
  tags:
    name: ${self:service}-${self:provider.stage}
  vpc:
    securityGroupIds:
      - sg-0d2e53ade40e60060
    subnetIds:
      - subnet-0126fe03fa91a38de
      - subnet-0386f8ab22bd7a664
  environment:
    NSG_DB_PASS: ${env:NSG_DB_PASS}
    SPLUNK_TOKEN: ${env:SPLUNK_TOKEN}

package:
  individually: true

functions:
  list:
    handler: src/crud.handler
    events:
      - http:
          method: GET
          path: api/v${self:custom.version}/table/{table}
          cors: true
  create:
    handler: src/crud.handler
    events:
      - http:
          method: POST
          path: api/v${self:custom.version}/table/{table}
          cors: true
  update:
    handler: src/crud.handler
    events:
      - http:
          method: PUT
          path: api/v${self:custom.version}/table/{table}/{id}
          cors: true
  delete:
    handler: src/crud.handler
    events:
      - http:
          method: DELETE
          path: api/v${self:custom.version}/table/{table}/{id}
          cors: true
  infoblox:
    handler: src/infoblox/infoblox.handler
    timeout: 30
    events:
      - http:
          method: GET
          path: api/v${self:custom.version}/infoblox/{endpoint}
          cors: true
  login:
    handler: src/auth/login.handler
    events:
      - http:
          method: GET
          path: api/v${self:custom.version}/auth/login
          cors: true
  page:
    handler: src/auth/page.handler
    events:
      - http:
          method: GET
          path: api/v${self:custom.version}/auth/page
          cors: true

custom:
  version: 1
  TeamManagedPolicy: !ImportValue fff000-iam-${self:provider.stage}-nsgtoolbox-01-TeamManagedPolicy
  webpack:
    webpackConfig: webpack.config.js
    includeModules: false

resources:
  Outputs:
    ApiHostname:
      Description: "The API Gateway URL for NSG"
      Value:
        Fn::Join:
          - ""
          - - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com"
      Export:
        Name: ApiHostname-v${self:custom.version}

plugins:
  - serverless-webpack
