service: nsg-acl

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: us-west-2
  stage: ${opt:stage, 'nonprod'}
  runtime: nodejs10.x
  environment:
    DYNAMODB_TABLE: ${self:custom.ACLTableName}

custom:
  ACLTableName: !ImportValue ACLTableName
  ACLTableARN: !ImportValue ACLTableARN
  TeamManagedPolicy: !ImportValue fff000-iam-${self:provider.stage}-nsgtoolbox-01-TeamManagedPolicy
  webpack:
    webpackConfig: webpack.config.js
    includeModules: false

package:
  individually: true

functions:
  create-access-list:
    handler: src/access-list/create.create
    events:
      - http:
          path: create
          method: post
          cors: true

  list:
    handler: src/list.list
    events:
      - http:
          path: list
          method: get
          cors: true

#   get:
#     handler: todos/get.get
#     events:
#       - http:
#           path: todos/{id}
#           method: get
#           cors: true

#   update:
#     handler: todos/update.update
#     events:
#       - http:
#           path: todos/{id}
#           method: put
#           cors: true

#   delete:
#     handler: todos/delete.delete
#     events:
#       - http:
#           method: delete
#           cors: true


plugins:
  - serverless-webpack
