service: nsg-acl-storage

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: us-west-2
  stage: ${opt:stage, 'nonprod'}
  runtime: nodejs10.x

resources:
  Resources:
    ACLTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:service}-${opt:stage, self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: prefix-list
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: prefix-list-index
            KeySchema:
              - AttributeName: prefix-list
                KeyType: HASH
            Projection:
              NonKeyAttributes: []
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
  
  Outputs:
    ACLTableExportName:
      Value: !Ref ACLTable
      Export:
        Name: ACLTableName
    ACLTableExportARN:
      Value: !GetAtt ACLTable.Arn
      Export:
        Name: ACLTableARN

  
